# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
spring.application.name=studentmvc

spring.datasource.url=postgresql://neondb_owner:npg_hBV7UbrO6xFw@ep-shy-violet-areytuyf-pooler.c-4.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=8080

